variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VIVADO_PATH_SH: '/nfs/data41/software/Xilinx/Vivado/${VIVADO_VERSION}/settings64.sh'
  PROJ_NAME: $CI_COMMIT_REF_NAME

stages: # ---------------------------------------------------------------------
#  - quality-check
  - hls-build
#  - topTF-build

# Job templates ---------------------------------------------------------------
.job_template: &template_base
  tags:
    - xilinx-tools
  before_script:
    - source $VIVADO_PATH_SH

.job_template: &template_hls-build
  <<: *template_base
  stage: hls-build
  script:
    - cd project
    - pwd; ls -la; #debug
    - vivado_hls -f "script_${PROJ_NAME}.tcl"
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - ./project/$PROJ_NAME/
    expire_in: 1 day
# Jobs ------------------------------------------------------------------------
VMR-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "VMR"
TE-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "TE"
  script:
    - cd emData/TE
    - ./download.sh
    - cd ../../project
    - pwd; ls -la; #debug
    - vivado_hls -f "script_${PROJ_NAME}.tcl"
TC-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "TC"
  script:
    - cd emData/TC
    - ./download.sh
    - cd ../../project
    - pwd; ls -la; #debug
    - vivado_hls -f "script_${PROJ_NAME}.tcl"
PR-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "PR"
ME-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "ME"
MC-hls-build:
  <<: *template_hls-build
  variables:
    VIVADO_VERSION: "2019.2"
    PROJ_NAME: "MC"





