name: HLS build on lnxfarm327
env:
  VIVADO_PATH_SH: '/nfs/data41/software/Xilinx/Vivado/2019.2/settings64.sh'
  
# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
  #    branches: [ master ]
  #  pull_request:
  #    branches: [ master ]
jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  hls-build: # Job name
    runs-on: self-hosted # The type of runner that the job will run on
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Debug # Script name
      run: |
        pwd; ls -a; ls -a project; ls -a $GITHUB_WORKSPACE; # Debug
    - name: MC # Script name
      run: |
        cd project
        source $VIVADO_PATH_SH
        vivado_hls -f "script_MC.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: MC
        path: project/match_calc/solution1/syn/report/MatchCalculatorTop_csynth.rpt
    - name: ME # Script name
      run: |
        cd project
        source $VIVADO_PATH_SH
        vivado_hls -f "script_ME.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: ME
        path: project/matchengine/solution1/syn/report/MatchEngineTop_csynth.rpt
    - name: PR # Script name
      run: |
        cd project
        source $VIVADO_PATH_SH
        vivado_hls -f "script_PR.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: PR
        path: project/projrouter/solution1/syn/report/ProjectionRouterTop_csynth.rpt
    - name: TC # Script name
      run: |
        cd project
        source $VIVADO_PATH_SH
        vivado_hls -f "script_TC.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: TC
        path: project/trackletCalculator/solution1/syn/report/TrackletCalculator_L1L2G_csynth.rpt
    # Does not work right now
#    - name: TE # Script name
#      run: |
#        cd project
#        source $VIVADO_PATH_SH
#        vivado_hls -f "script_TE.tcl"
